### ISSUE TITLE
mace bug or bugs

### ISSUE THREAD

**Issue by Fulanote** [Jusey1/TrialsChambersBackport#11]
1.the mace enchanted with wind burst sometimes elevates entities more than oneself

the original mace the wind burst effect (the moment of the hit) does not come from the height of the attacked entity, it comes from the height of the player. in the backport(mod) it always comes from the height of the entity making the entity also go up, especially when you hit at the same height or below it

2. I don't know if it's a bug but every time I receive damage specifically with the windburst effect (the moment of the rise and the fall) I fall quickly to the ground and that doesn't happen with other types of damage while I fall in the same version

(after a few minutes of testing and fun, that's my explanation)

edit-the mace does not break the vases into pieces

**Comment by Jusey1** [comment]
All of this is being fixed up for v2.1.7!~

**Comment by Fulanote** [comment]
1 and 3 (edit) are solved
but the 2nd problem is still present
when taking damage from projectiles or potions such as wither and poison, basically any damage really

and the wind charge could be much faster or at the same speed as a snow ball and ender pearl but without deviating, because when jumping from a great height [ex:end pillars or higher] the wind charge is not fast enough
thanks for the attention
