### ISSUE TITLE
Suggestion: Allow Vaults to pull from other loot tables

### ISSUE THREAD

**Issue by LenKagamine** [Jusey1/TrialsChambersBackport#13]
I don't know if there's already a way to do this and I'm just doing it wrong, but it would be cool if both Trial Vaults and Ominous Trial Vaults could pull from different loot tables using NBT. Like how you can use a command to give a chest with a specific loot table. It would help both modpack and datapack makers make custom trial structures using this mod.

**Comment by Jusey1** [comment]
Ye'h, I should probably do this at some point, just been taking a break from coding for right now so I can focus on playing the game for once.

**Comment by LenKagamine** [comment]
Ok, that sounds good. I also just realized that the trial spawners themselves have a pool they take from, too.

**Comment by Jusey1** [comment]
Completed as of v2.2.1.
