### ISSUE TITLE
Question: Custom Loot Tables

### ISSUE THREAD

**Issue by dabomb6405** [Jusey1/TrialsChambersBackport#15]
In the most recent update, the changelog mentioned you can now make custom loot tables for spawners and vaults. How exactly does this work? Are you able to add spawners and vaults to other structures and give them unique loot tables, or are you only able to edit the base vault and spawner loot tables?

And if it is adding custom loot tables for new structures, how exactly do you do that?

**Comment by Jusey1** [comment]
Via commands, just like with any container which can have a loot table.
